const actionTypes= {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGIN_SUCCEED:"LOGIN_SUCCEED",
    LOAD_PRODUCTS:"LOAD_PRODUCTS",
    PRODUCTS_FETCH_SUCCEEDED:"PRODUCTS_FETCH_SUCCEEDED",
    SEARCH_REQUEST:"SEARCH_REQUEST",
    SEARCH_REQUEST_SUCCEEDED:"SEARCH_REQUEST_SUCCEED",
    SEARCH_REQUEST_FAILURE:"SEARCH_REQUEST_FAILURE",
    CHANGE_PAGE:"CHANGE_PAGA",
    CHANGE_PAGE_SUCCEEDED:"CHANGE_PAGE_SUCCEEDED",
    CHANGE_PAGE_FAILURE:"CHANGE_PAGE_FAILURE",
}
export default actionTypes